"""empty message

Revision ID: 3b245798d885
Revises: 503642386bd4
Create Date: 2015-11-26 20:51:02.991000

"""

# revision identifiers, used by Alembic.
revision = '3b245798d885'
down_revision = '503642386bd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
