"""empty message

Revision ID: 503642386bd4
Revises: 56fe3c9c5088
Create Date: 2015-11-22 16:18:50.195000

"""

# revision identifiers, used by Alembic.
revision = '503642386bd4'
down_revision = '56fe3c9c5088'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
